//
//  NotePDFRendererTests.swift
//  CaseNotesTests
//
//  Created by q on 8/29/26.
//

import Foundation
import PDFKit
import PencilKit
import Testing
@testable import CaseNotes

@MainActor
struct NotePDFRendererTests {
    /// Fixed locale and time zone so the event date is asserted on exactly,
    /// rather than following whichever region the test machine is set to.
    private let locale = Locale(identifier: "en_US_POSIX")
    private let timeZone = TimeZone(identifier: "GMT")!
    private let eventDate = Date(timeIntervalSince1970: 1_700_086_400)

    private func pdfData(
        title: String = "Site Visit",
        eventDate: Date? = nil,
        body: String = "",
        drawingData: Data? = nil
    ) -> Data {
        NotePDFRenderer.pdfData(
            for: NotePDFRenderer.Content(
                title: title,
                eventDate: eventDate,
                body: body,
                drawingData: drawingData
            ),
            locale: locale,
            timeZone: timeZone
        )
    }

    /// Reads the document back with PDFKit.
    ///
    /// Loading the generated bytes is the check that they really are a PDF, and
    /// extracting the text is the check that the note was typeset rather than
    /// screenshotted: a page of pixels would come back with nothing in it.
    private func document(_ data: Data) throws -> PDFDocument {
        try #require(PDFDocument(data: data))
    }

    private func text(of data: Data) throws -> String {
        try document(data).string ?? ""
    }

    /// A drawing with straight strokes, built in code so the tests stay free of
    /// recorded fixtures.
    private func makeDrawing(strokes: Int = 1, length: CGFloat = 60) -> PKDrawing {
        let ink = PKInk(.pen, color: .black)

        let strokeList = (0..<strokes).map { index -> PKStroke in
            let offset = CGFloat(index) * 20
            let points = [
                PKStrokePoint(
                    location: CGPoint(x: offset, y: 0),
                    timeOffset: 0,
                    size: CGSize(width: 4, height: 4),
                    opacity: 1,
                    force: 1,
                    azimuth: 0,
                    altitude: 0
                ),
                PKStrokePoint(
                    location: CGPoint(x: offset + 40, y: length),
                    timeOffset: 0.1,
                    size: CGSize(width: 4, height: 4),
                    opacity: 1,
                    force: 1,
                    azimuth: 0,
                    altitude: 0
                ),
            ]

            return PKStroke(
                ink: ink,
                path: PKStrokePath(controlPoints: points, creationDate: Date())
            )
        }

        return PKDrawing(strokes: strokeList)
    }

    // MARK: - Document validity

    @Test
    func outputIsAValidPDFDocument() throws {
        let data = pdfData(body: "Walked the north wing.")

        #expect(data.prefix(4) == Data("%PDF".utf8))
        #expect(try document(data).pageCount >= 1)
    }

    @Test
    func aNoteProducesAtLeastOnePageAndNoBlankFirstPage() throws {
        let data = pdfData(title: "Site Visit", body: "Walked the north wing.")
        let pdf = try document(data)

        #expect(pdf.pageCount == 1)
        #expect(try #require(pdf.page(at: 0)?.string).contains("Site Visit"))
    }

    @Test
    func textIsExtractableRatherThanRasterized() throws {
        let body = "The stairwell lighting is still out and the east door does not latch."

        #expect(try text(of: pdfData(body: body)).contains("stairwell lighting"))
    }

    // MARK: - Authored content

    @Test
    func theTitleLeadsTheDocument() throws {
        #expect(try text(of: pdfData(title: "Site Visit")).contains("Site Visit"))
    }

    @Test
    func theBodyIsIncluded() throws {
        let data = pdfData(body: "Walked the north wing with facilities.")

        #expect(try text(of: data).contains("Walked the north wing with facilities."))
    }

    @Test
    func theEventDateIsIncludedWhenPresent() throws {
        let data = pdfData(eventDate: eventDate, body: "Walked the north wing.")

        #expect(try text(of: data).contains("November 15, 2023"))
    }

    @Test
    func theEventDateLineIsOmittedWhenAbsent() throws {
        #expect(try !text(of: pdfData(body: "Walked the north wing.")).contains("Event date"))
    }

    @Test
    func internalMetadataIsExcluded() throws {
        let extracted = try text(
            of: pdfData(eventDate: eventDate, body: "Walked the north wing.")
        )

        #expect(!extracted.localizedCaseInsensitiveContains("pinned"))
        #expect(!extracted.localizedCaseInsensitiveContains("created"))
        #expect(!extracted.localizedCaseInsensitiveContains("edited"))
        #expect(!extracted.localizedCaseInsensitiveContains("updated"))
        #expect(!extracted.localizedCaseInsensitiveContains("folder"))
        #expect(!extracted.localizedCaseInsensitiveContains("revision"))
    }

    @Test
    func anEmptyBodyStillProducesATitledDocument() throws {
        let data = pdfData(title: "Site Visit", body: "   \n  ")
        let pdf = try document(data)

        #expect(pdf.pageCount == 1)
        #expect(try #require(pdf.string).contains("Site Visit"))
    }

    // MARK: - Markdown rendering

    @Test
    func markdownStructureIsRenderedRatherThanShownAsSource() throws {
        let body = """
        ## Actions

        - Photograph the stairwell
        - Check the **handrail**

        1. Raise a ticket

        > Parts are on order.

        Use `notes.export()` or see the [handbook](https://example.com).

        ```swift
        let note = Note(title: "Site Visit")
        ```
        """

        let extracted = try text(of: pdfData(body: body))

        #expect(extracted.contains("Actions"))
        #expect(extracted.contains("Photograph the stairwell"))
        #expect(extracted.contains("handrail"))
        #expect(extracted.contains("Raise a ticket"))
        #expect(extracted.contains("Parts are on order."))
        #expect(extracted.contains("notes.export()"))
        #expect(extracted.contains("handbook"))
        #expect(extracted.contains("let note = Note(title:"))

        // The syntax itself resolved into presentation rather than surviving as
        // characters on the page.
        #expect(!extracted.contains("## Actions"))
        #expect(!extracted.contains("**handrail**"))
        #expect(!extracted.contains("[handbook]"))
        #expect(!extracted.contains("```"))
    }

    @Test
    func aLinkKeepsItsTextAndBecomesAFollowableAnnotation() throws {
        let data = pdfData(body: "See the [handbook](https://example.com/handbook).")
        let pdf = try document(data)
        let page = try #require(pdf.page(at: 0))

        #expect(try #require(page.string).contains("handbook"))

        let urls = page.annotations.compactMap(\.url?.absoluteString)
        #expect(urls.contains("https://example.com/handbook"))
    }

    @Test
    func aLinkAnnotationSitsOverTheTextItLabels() throws {
        let data = pdfData(body: "See the [handbook](https://example.com/handbook).")
        let page = try #require(try document(data).page(at: 0))
        let annotation = try #require(page.annotations.first { $0.url != nil })
        let bounds = annotation.bounds
        let pageBounds = page.bounds(for: .mediaBox)

        #expect(pageBounds.contains(bounds))
        // The note is one short line, so its link belongs in the upper part of
        // the page. A vertically mirrored rectangle would land in the lower part.
        #expect(bounds.midY > pageBounds.midY)
    }

    @Test
    func malformedMarkdownStillProducesAReadableDocument() throws {
        let body = "Unclosed [link and **bold and `code, plus a stray ]( and ```"

        let extracted = try text(of: pdfData(body: body))

        #expect(extracted.contains("Unclosed"))
        #expect(extracted.contains("stray"))
    }

    @Test
    func unicodeContentRendersWithoutFailing() throws {
        let data = pdfData(
            title: "Besichtigung Nordflügel 現場調査 \u{1F5FA}",
            body: "Café notes: naïve façade, 東棟の階段, emoji \u{1F58A} and \u{2192} arrows."
        )

        let extracted = try text(of: data)

        #expect(extracted.contains("Nordfl"))
        #expect(extracted.contains("façade"))
    }

    @Test
    func aLongTitleWrapsRatherThanBeingLost() throws {
        let title = String(repeating: "Northern wing corridor survey ", count: 8)
        let data = pdfData(title: title, body: "Walked the north wing.")

        let extracted = try text(of: data)

        #expect(extracted.contains("Northern wing corridor survey"))
        #expect(extracted.contains("Walked the north wing."))
    }

    // MARK: - Thematic breaks and folding

    @Test
    func everyRegionOfANoteWithThematicBreaksIsExported() throws {
        let body = """
        Intro before any break.

        ---

        The middle region.

        ---

        The closing region.
        """

        let extracted = try text(of: pdfData(body: body))

        #expect(extracted.contains("Intro before any break."))
        #expect(extracted.contains("The middle region."))
        #expect(extracted.contains("The closing region."))
    }

    @Test
    func thematicBreaksCarryNoReadModeFoldingAffordances() throws {
        let body = """
        # Overview

        Intro.

        ---

        Details.
        """

        let extracted = try text(of: pdfData(body: body))

        #expect(!extracted.localizedCaseInsensitiveContains("collapsed"))
        #expect(!extracted.localizedCaseInsensitiveContains("expanded"))
        #expect(!extracted.localizedCaseInsensitiveContains("section collapsed"))
        #expect(!extracted.contains("chevron"))
    }

    @Test
    func aPlacedAttachmentIsLeftOutAndCostsTheNoteNothingElse() throws {
        let identifier = UUID(uuidString: "3F2504E0-4F89-11D3-9A0C-0305E82C3301")!
        let body = """
        Walked the north wing.

        \(InlineAttachmentMarker.text(for: identifier))

        Photograph the stairwell next time.
        """

        let extracted = try text(of: pdfData(body: body))

        // A PDF carries authored content, and a note's files have never been
        // part of that. The reference is not drawn, and neither is its raw
        // syntax, which would be worse than leaving it out.
        #expect(extracted.contains("Walked the north wing."))
        #expect(extracted.contains("Photograph the stairwell next time."))
        #expect(!extracted.contains(identifier.uuidString))
        #expect(!extracted.contains("{{attachment"))
    }

    @Test
    func aMarkerInsideCodeStillExportsAsTheCodeItIs() throws {
        let identifier = UUID(uuidString: "3F2504E0-4F89-11D3-9A0C-0305E82C3301")!
        let body = "```\n\(InlineAttachmentMarker.text(for: identifier))\n```"

        let extracted = try text(of: pdfData(body: body))

        #expect(extracted.contains("{{attachment"))
    }

    @Test
    func theRendererTakesNoCollapsedStateAtAll() {
        // The exporter's whole input is authored content. There is nowhere for a
        // reading view's fold state to enter, which is the invariant rather than
        // a behavior to be remembered.
        let content = NotePDFRenderer.Content(
            title: "Site Visit",
            body: "Intro.\n\n---\n\nDetails."
        )

        #expect(
            content == NotePDFRenderer.Content(
                title: "Site Visit",
                eventDate: nil,
                body: "Intro.\n\n---\n\nDetails.",
                drawingData: nil
            )
        )
    }

    // MARK: - Pagination

    @Test
    func aLongNoteProducesMultiplePages() throws {
        let paragraph = """
        The stairwell lighting on the north side is still out, the east door \
        does not latch, and the ramp handrail is loose at its lower bracket.
        """
        let body = Array(repeating: paragraph, count: 90).joined(separator: "\n\n")

        let pdf = try document(pdfData(body: body))

        #expect(pdf.pageCount > 1)
        #expect(try #require(pdf.page(at: pdf.pageCount - 1)?.string).contains("handrail"))
    }

    @Test
    func aParagraphTooLongForOnePageContinuesOnTheNext() throws {
        let sentence = "The corridor was inspected end to end and logged. "
        let body = "OpeningMarker. " + String(repeating: sentence, count: 400) + " ClosingMarker."

        let pdf = try document(pdfData(body: body))

        #expect(pdf.pageCount > 1)
        #expect(try #require(pdf.string).contains("OpeningMarker"))
        #expect(try #require(pdf.string).contains("ClosingMarker"))
    }

    @Test
    func aListCrossingAPageBoundaryKeepsEveryItem() throws {
        let items = (1...140).map { "- Inspection point number \($0) recorded" }
        let body = items.joined(separator: "\n")

        let pdf = try document(pdfData(body: body))
        let extracted = try #require(pdf.string)

        #expect(pdf.pageCount > 1)
        #expect(extracted.contains("Inspection point number 1 recorded"))
        #expect(extracted.contains("Inspection point number 140 recorded"))
    }

    @Test
    func aCodeBlockNearAPageBoundaryKeepsEveryLine() throws {
        let filler = Array(repeating: "Corridor inspected and logged.", count: 40)
            .joined(separator: "\n\n")
        let code = (1...60).map { "let inspectionPoint\($0) = Note(title: \"Point \($0)\")" }
            .joined(separator: "\n")
        let body = "\(filler)\n\n```swift\n\(code)\n```"

        let pdf = try document(pdfData(body: body))
        let extracted = try #require(pdf.string)

        #expect(pdf.pageCount > 1)
        #expect(extracted.contains("let inspectionPoint1 ="))
        #expect(extracted.contains("let inspectionPoint60 ="))
    }

    @Test
    func aLongCodeLineWrapsRatherThanRunningOffThePage() throws {
        let token = String(repeating: "veryLongIdentifierSegment", count: 12)
        let body = "```\n\(token)\n```"

        let extracted = try text(of: pdfData(body: body))

        // Character wrapping splits the run across lines, so the whole token is
        // present but not as one uninterrupted extracted string.
        #expect(extracted.contains("veryLongIdentifierSegment"))
        #expect(extracted.replacingOccurrences(of: "\n", with: "").contains(token))
    }

    @Test
    func aNoteEndingAtAPageBoundaryAddsNoBlankTrailingPage() throws {
        let paragraph = "The corridor was inspected end to end and logged for review."
        var pageCounts: Set<Int> = []

        // Sweeping the length walks the body across page boundaries one
        // paragraph at a time, so a length that lands exactly on a boundary and
        // spills an empty page is covered rather than hoped for.
        for count in 1...60 {
            let body = Array(repeating: paragraph, count: count).joined(separator: "\n\n")
            let pdf = try document(pdfData(body: body))
            let lastPage = try #require(pdf.page(at: pdf.pageCount - 1)?.string)

            #expect(!lastPage.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)
            pageCounts.insert(pdf.pageCount)
        }

        #expect(pageCounts.count > 1)
    }

    // MARK: - Drawings

    @Test
    func aNoteWithoutADrawingExports() throws {
        let pdf = try document(pdfData(body: "Walked the north wing."))

        #expect(pdf.pageCount == 1)
        #expect(try #require(pdf.string).contains("Walked the north wing."))
    }

    @Test
    func aValidDrawingIsIncludedAfterTheText() throws {
        let drawing = makeDrawing(strokes: 4)
        let data = try #require(DrawingCodec.encode(drawing))

        let withDrawing = pdfData(body: "Walked the north wing.", drawingData: data)
        let withoutDrawing = pdfData(body: "Walked the north wing.")

        #expect(try text(of: withDrawing).contains("Walked the north wing."))
        // The rasterized sketch is the only difference between the two runs.
        #expect(withDrawing.count > withoutDrawing.count)
    }

    @Test
    func anEmptyDrawingAddsNoContent() throws {
        let empty = PKDrawing().dataRepresentation()

        let withEmpty = pdfData(body: "Walked the north wing.", drawingData: empty)
        let withNone = pdfData(body: "Walked the north wing.")

        #expect(try document(withEmpty).pageCount == document(withNone).pageCount)
        #expect(try text(of: withEmpty) == text(of: withNone))
    }

    @Test
    func corruptDrawingDataDoesNotPreventTheTextFromExporting() throws {
        let corrupt = Data([0xDE, 0xAD, 0xBE, 0xEF, 0x00, 0x01, 0x02, 0x03])

        let data = pdfData(
            title: "Site Visit",
            body: "Walked the north wing.",
            drawingData: corrupt
        )

        let pdf = try document(data)
        #expect(pdf.pageCount == 1)
        #expect(try #require(pdf.string).contains("Walked the north wing."))
    }

    @Test
    func aTallDrawingIsScaledToTheDocumentRatherThanClipped() throws {
        let drawing = makeDrawing(strokes: 2, length: 4000)
        let data = try #require(DrawingCodec.encode(drawing))

        let pdf = try document(pdfData(body: "Walked the north wing.", drawingData: data))

        // A drawing taller than a page moves to its own page and is scaled to
        // fit it, so the note stays two pages rather than growing without limit.
        #expect(pdf.pageCount == 2)
        #expect(try #require(pdf.page(at: 0)?.string).contains("Walked the north wing."))
    }

    @Test
    func aDrawingAfterANearlyFullPageMovesToTheNextPage() throws {
        let paragraph = "The corridor was inspected end to end and logged for review."
        let body = Array(repeating: paragraph, count: 44).joined(separator: "\n\n")
        let drawing = try #require(DrawingCodec.encode(makeDrawing(strokes: 3)))

        let withDrawing = try document(pdfData(body: body, drawingData: drawing))
        let withoutDrawing = try document(pdfData(body: body))

        #expect(withDrawing.pageCount >= withoutDrawing.pageCount)
    }

    // MARK: - Content capture

    @Test
    func contentCapturesAuthoredValuesFromANote() {
        let note = Note(
            title: "Site Visit",
            body: "Walked the north wing.",
            createdAt: Date(timeIntervalSince1970: 1_700_000_000),
            updatedAt: Date(timeIntervalSince1970: 1_700_000_100),
            isPinned: true,
            eventDate: eventDate
        )

        let content = NotePDFRenderer.Content(note: note)

        #expect(content.title == "Site Visit")
        #expect(content.body == "Walked the north wing.")
        #expect(content.eventDate == eventDate)
        #expect(content.drawingData == nil)
    }

    @Test
    func contentUsesTheTitlePlaceholderForAnUntitledNote() {
        let content = NotePDFRenderer.Content(note: Note(title: "   "))

        #expect(content.title == "Untitled Note")
    }

    // MARK: - File packaging

    @Test
    func theExportedFileNameMatchesTheMarkdownPolicy() {
        let note = Note(title: "Budget: Q3/Q4 <draft>")

        #expect(NoteExport.suggestedPDFFileName(for: note) == "Budget Q3 Q4 draft.pdf")
        #expect(
            NoteExport.suggestedPDFFileName(for: note)
                == "\(NoteExport.fileBaseName(for: note)).pdf"
        )
    }

    @Test
    func theSharedFileRendersTheNoteItPackaged() async throws {
        let note = Note(
            title: "Site Visit",
            body: "Walked the north wing.",
            eventDate: eventDate
        )

        let file = PDFNoteFile(note: note, locale: locale, timeZone: timeZone)
        #expect(file.fileName == "Site Visit.pdf")

        let extracted = try text(of: await file.pdfData())
        #expect(extracted.contains("Site Visit"))
        #expect(extracted.contains("Walked the north wing."))
        #expect(extracted.contains("November 15, 2023"))
    }
}
